export interface CalendarEventOptions {
  title: string;
  description: string;
  location: string;
  dueDate: string; // YYYY-MM-DD
  priority?: string;
  auditorName?: string;
}

/**
 * Dynamically computes a smart default due date based on venue schedule or priority SLA.
 */
export function calculateDynamicDueDate(
  venue?: { nextAuditDueDate?: string; scheduleFrequencyDays?: number },
  priority?: string
): string {
  const today = new Date();
  
  // 1. If venue has an explicit scheduled due date from registry, use it
  if (venue?.nextAuditDueDate && venue.nextAuditDueDate.trim() !== '') {
    return venue.nextAuditDueDate;
  }
  
  // 2. Otherwise calculate based on priority SLA offset
  let daysToAdd = 7; // Default medium priority standard
  if (priority === 'HIGH' || priority === 'URGENT') {
    daysToAdd = 3;
  } else if (priority === 'LOW' || priority === 'ROUTINE') {
    daysToAdd = 14;
  } else if (venue?.scheduleFrequencyDays && venue.scheduleFrequencyDays > 0) {
    daysToAdd = venue.scheduleFrequencyDays;
  }
  
  const targetDate = new Date(today.getTime() + daysToAdd * 86400000);
  return targetDate.toISOString().split('T')[0];
}

/**
 * Format a YYYY-MM-DD date into YYYYMMDDTHHmmssZ for calendar URLs (UTC time: 09:00:00 to 17:00:00 local standard)
 */
function formatCalendarDates(dueDateStr: string): { startStr: string; endStr: string; isoStart: string; isoEnd: string } {
  try {
    const parts = dueDateStr.split('-');
    if (parts.length === 3) {
      const year = parseInt(parts[0], 10);
      const month = parseInt(parts[1], 10) - 1;
      const day = parseInt(parts[2], 10);
      
      const start = new Date(Date.UTC(year, month, day, 9, 0, 0));
      const end = new Date(Date.UTC(year, month, day, 17, 0, 0));
      
      const formatUtc = (d: Date) => d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
      
      return {
        startStr: formatUtc(start),
        endStr: formatUtc(end),
        isoStart: start.toISOString(),
        isoEnd: end.toISOString()
      };
    }
  } catch (e) {
    console.error('Date parsing error:', e);
  }
  
  // Fallback
  const now = new Date();
  const cleanNow = now.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  return {
    startStr: cleanNow,
    endStr: cleanNow,
    isoStart: now.toISOString(),
    isoEnd: now.toISOString()
  };
}

/**
 * Generates a pre-filled Google Calendar web URL
 */
export function getGoogleCalendarUrl(event: CalendarEventOptions): string {
  const { startStr, endStr } = formatCalendarDates(event.dueDate);
  const title = encodeURIComponent(`[FC Audit] ${event.title}`);
  const details = encodeURIComponent(
    `Campus Fitness Certificate (FC) Audit Task\n\n` +
    `📍 Location: ${event.location}\n` +
    `⚡ Priority: ${event.priority || 'NORMAL'}\n` +
    `👤 Auditor: ${event.auditorName || 'Assigned Certified Auditor'}\n` +
    `📝 Notes: ${event.description}\n\n` +
    `Generated by Campus FC Smart Audit System`
  );
  const location = encodeURIComponent(event.location);
  
  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${startStr}/${endStr}&details=${details}&location=${location}`;
}

/**
 * Generates a pre-filled Outlook / Office 365 Web Calendar URL
 */
export function getOutlookCalendarUrl(event: CalendarEventOptions): string {
  const { isoStart, isoEnd } = formatCalendarDates(event.dueDate);
  const subject = encodeURIComponent(`[FC Audit] ${event.title}`);
  const body = encodeURIComponent(
    `Campus Fitness Certificate (FC) Audit Task\n\n` +
    `📍 Location: ${event.location}\n` +
    `⚡ Priority: ${event.priority || 'NORMAL'}\n` +
    `👤 Auditor: ${event.auditorName || 'Assigned Certified Auditor'}\n` +
    `📝 Notes: ${event.description}\n\n` +
    `Generated by Campus FC Smart Audit System`
  );
  const location = encodeURIComponent(event.location);
  
  return `https://outlook.live.com/calendar/0/deeplink/compose?subject=${subject}&startdt=${isoStart}&enddt=${isoEnd}&body=${body}&location=${location}`;
}

/**
 * Generates and triggers download of an iCalendar (.ics) file
 */
export function downloadIcsFile(event: CalendarEventOptions): void {
  const { startStr, endStr } = formatCalendarDates(event.dueDate);
  const uid = `fc-audit-${Date.now()}-${Math.random().toString(36).substring(2, 7)}@bitsathy.ac.in`;
  const cleanDescription = (event.description || '').replace(/\n/g, '\\n');
  
  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Campus FC Smart Audit System//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${startStr}`,
    `DTSTART:${startStr}`,
    `DTEND:${endStr}`,
    `SUMMARY:[FC Audit] ${event.title}`,
    `DESCRIPTION:${cleanDescription} | Priority: ${event.priority || 'NORMAL'}`,
    `LOCATION:${event.location}`,
    'STATUS:CONFIRMED',
    `PRIORITY:${event.priority === 'HIGH' || event.priority === 'URGENT' ? 1 : 5}`,
    'BEGIN:VALARM',
    'TRIGGER:-PT24H',
    'ACTION:DISPLAY',
    'DESCRIPTION:Reminder: Campus FC Audit Due Tomorrow',
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');
  
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `FC-Audit-${event.title.replace(/[^a-zA-Z0-9]/g, '_')}-${event.dueDate}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
